[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.49", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
chrono = "0.4"
pgvector = "0.4"
dotenvy = "0.15"

[dependencies.sea-orm]
version = "2.0.0-rc.28"
features = ["debug-print", "runtime-tokio-rustls", "sqlx-postgres", "pgvector"]

[dependencies.salvo]
version = "0.88"
features = ["anyhow", "affix-state", "tower-compat", "oapi"]
