//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "cut_credits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub cut_id: Uuid,
    pub person_id: Uuid,
    pub job: String,
    pub is_sure: bool,
    pub summary: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub info: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cuts::Entity",
        from = "Column::CutId",
        to = "super::cuts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cuts,
    #[sea_orm(
        belongs_to = "super::persons::Entity",
        from = "Column::PersonId",
        to = "super::persons::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Persons,
}

impl Related<super::cuts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cuts.def()
    }
}

impl Related<super::persons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
