//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::WikiStatus;
use super::sea_orm_active_enums::WorkScope;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "cuts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub is_nsfw: bool,
    pub wiki_status: WikiStatus,
    pub work_id: Option<Uuid>,
    pub scope_type: Option<WorkScope>,
    pub scope_number: Option<i32>,
    pub start_time: Option<String>,
    pub end_time: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub summary: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub info: Option<Json>,
    pub posted_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cut_credits::Entity")]
    CutCredits,
    #[sea_orm(has_many = "super::cuts_metatags::Entity")]
    CutsMetatags,
    #[sea_orm(has_many = "super::cuts_resources::Entity")]
    CutsResources,
    #[sea_orm(has_many = "super::cuts_tags::Entity")]
    CutsTags,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::PostedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::works::Entity",
        from = "Column::WorkId",
        to = "super::works::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Works,
}

impl Related<super::cut_credits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CutCredits.def()
    }
}

impl Related<super::cuts_metatags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CutsMetatags.def()
    }
}

impl Related<super::cuts_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CutsResources.def()
    }
}

impl Related<super::cuts_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CutsTags.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::works::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Works.def()
    }
}

impl Related<super::metatags::Entity> for Entity {
    fn to() -> RelationDef {
        super::cuts_metatags::Relation::Metatags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cuts_metatags::Relation::Cuts.def().rev())
    }
}

impl Related<super::resources::Entity> for Entity {
    fn to() -> RelationDef {
        super::cuts_resources::Relation::Resources.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cuts_resources::Relation::Cuts.def().rev())
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::cuts_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cuts_tags::Relation::Cuts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
