//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "cuts_resources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cut_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub resource_id: Uuid,
    pub usage: String,
    pub sort_order: i32,
    pub votes: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cuts::Entity",
        from = "Column::CutId",
        to = "super::cuts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cuts,
    #[sea_orm(
        belongs_to = "super::resources::Entity",
        from = "Column::ResourceId",
        to = "super::resources::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Resources,
}

impl Related<super::cuts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cuts.def()
    }
}

impl Related<super::resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Resources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
