//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "cuts_metatags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cut_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub metatag_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cuts::Entity",
        from = "Column::CutId",
        to = "super::cuts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cuts,
    #[sea_orm(
        belongs_to = "super::metatags::Entity",
        from = "Column::MetatagId",
        to = "super::metatags::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Metatags,
}

impl Related<super::cuts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cuts.def()
    }
}

impl Related<super::metatags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Metatags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
