//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "metatags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub slug: String,
    pub category: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub name: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub description: Json,
    pub ref_count: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cuts_metatags::Entity")]
    CutsMetatags,
}

impl Related<super::cuts_metatags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CutsMetatags.def()
    }
}

impl Related<super::cuts::Entity> for Entity {
    fn to() -> RelationDef {
        super::cuts_metatags::Relation::Cuts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cuts_metatags::Relation::Metatags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
