//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod cut_credits;
pub mod cuts;
pub mod cuts_metatags;
pub mod cuts_resources;
pub mod cuts_tags;
pub mod metatags;
pub mod permissions;
pub mod persons;
pub mod resources;
pub mod roles;
pub mod roles_permissions;
pub mod sea_orm_active_enums;
pub mod studios;
pub mod tags;
pub mod users;
pub mod users_roles;
pub mod work_credits;
pub mod works;
pub mod works_resources;
