//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::WikiStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "persons")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub name_translations: Option<Json>,
    pub wiki_status: WikiStatus,
    pub image_resource_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub summary: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub info: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cut_credits::Entity")]
    CutCredits,
    #[sea_orm(
        belongs_to = "super::resources::Entity",
        from = "Column::ImageResourceId",
        to = "super::resources::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Resources,
    #[sea_orm(has_many = "super::work_credits::Entity")]
    WorkCredits,
}

impl Related<super::cut_credits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CutCredits.def()
    }
}

impl Related<super::resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Resources.def()
    }
}

impl Related<super::work_credits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkCredits.def()
    }
}

impl Related<super::cuts::Entity> for Entity {
    fn to() -> RelationDef {
        super::cut_credits::Relation::Persons.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cut_credits::Relation::Persons.def().rev())
    }
}

impl Related<super::works::Entity> for Entity {
    fn to() -> RelationDef {
        super::work_credits::Relation::Persons.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::work_credits::Relation::Persons.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
