//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::cut_credits::Entity as CutCredits;
pub use super::cuts::Entity as Cuts;
pub use super::cuts_metatags::Entity as CutsMetatags;
pub use super::cuts_resources::Entity as CutsResources;
pub use super::cuts_tags::Entity as CutsTags;
pub use super::metatags::Entity as Metatags;
pub use super::permissions::Entity as Permissions;
pub use super::persons::Entity as Persons;
pub use super::resources::Entity as Resources;
pub use super::roles::Entity as Roles;
pub use super::roles_permissions::Entity as RolesPermissions;
pub use super::studios::Entity as Studios;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
pub use super::users_roles::Entity as UsersRoles;
pub use super::work_credits::Entity as WorkCredits;
pub use super::works::Entity as Works;
pub use super::works_resources::Entity as WorksResources;
