//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "resources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub storage_key: String,
    pub bucket: String,
    pub category: String,
    pub mime_type: String,
    pub file_size_bytes: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cuts_resources::Entity")]
    CutsResources,
    #[sea_orm(has_many = "super::persons::Entity")]
    Persons,
    #[sea_orm(has_many = "super::studios::Entity")]
    Studios,
    #[sea_orm(has_many = "super::works_resources::Entity")]
    WorksResources,
}

impl Related<super::cuts_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CutsResources.def()
    }
}

impl Related<super::persons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persons.def()
    }
}

impl Related<super::studios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Studios.def()
    }
}

impl Related<super::works_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorksResources.def()
    }
}

impl Related<super::cuts::Entity> for Entity {
    fn to() -> RelationDef {
        super::cuts_resources::Relation::Cuts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cuts_resources::Relation::Resources.def().rev())
    }
}

impl Related<super::works::Entity> for Entity {
    fn to() -> RelationDef {
        super::works_resources::Relation::Works.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::works_resources::Relation::Resources.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
