//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_status")]
pub enum UserStatus {
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "banned")]
    Banned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "wiki_status")]
pub enum WikiStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "locked")]
    Locked,
    #[sea_orm(string_value = "hidden")]
    Hidden,
    #[sea_orm(string_value = "deleted")]
    Deleted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "work_scope")]
pub enum WorkScope {
    #[sea_orm(string_value = "full")]
    Full,
    #[sea_orm(string_value = "episode")]
    Episode,
    #[sea_orm(string_value = "opening")]
    Opening,
    #[sea_orm(string_value = "ending")]
    Ending,
}
