//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub ref_count: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cuts_tags::Entity")]
    CutsTags,
}

impl Related<super::cuts_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CutsTags.def()
    }
}

impl Related<super::cuts::Entity> for Entity {
    fn to() -> RelationDef {
        super::cuts_tags::Relation::Cuts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cuts_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
