//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::UserStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub totp_enabled: bool,
    pub totp_secret_enc: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub recover_codes_enc: Option<Json>,
    pub token_version: i32,
    pub email_verified: bool,
    pub user_status: UserStatus,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cuts::Entity")]
    Cuts,
    #[sea_orm(has_many = "super::users_roles::Entity")]
    UsersRoles,
}

impl Related<super::cuts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cuts.def()
    }
}

impl Related<super::users_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersRoles.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::users_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::users_roles::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
