//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::WikiStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "works")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub name_translations: Option<Json>,
    pub wiki_status: WikiStatus,
    pub is_nsfw: bool,
    pub category: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub summary: Option<Json>,
    pub release_datetime: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub info: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cuts::Entity")]
    Cuts,
    #[sea_orm(has_many = "super::work_credits::Entity")]
    WorkCredits,
    #[sea_orm(has_many = "super::works_resources::Entity")]
    WorksResources,
}

impl Related<super::cuts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cuts.def()
    }
}

impl Related<super::work_credits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkCredits.def()
    }
}

impl Related<super::works_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorksResources.def()
    }
}

impl Related<super::resources::Entity> for Entity {
    fn to() -> RelationDef {
        super::works_resources::Relation::Resources.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::works_resources::Relation::Works.def().rev())
    }
}

impl Related<super::persons::Entity> for Entity {
    fn to() -> RelationDef {
        super::work_credits::Relation::Persons.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::work_credits::Relation::Works.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
