//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::WorkScope;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "work_credits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub work_id: Uuid,
    pub person_id: Uuid,
    pub position: String,
    pub scope_type: Option<WorkScope>,
    pub scope_number: Option<i32>,
    pub summary: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub info: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::persons::Entity",
        from = "Column::PersonId",
        to = "super::persons::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Persons,
    #[sea_orm(
        belongs_to = "super::works::Entity",
        from = "Column::WorkId",
        to = "super::works::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Works,
}

impl Related<super::persons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persons.def()
    }
}

impl Related<super::works::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Works.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
